### ISSUE TITLE
Missing databaseURL not present in firebaseConfig

### ISSUE THREAD

**Issue by Yaccoub** [guilhermeborgesbastos/live-resume#109]
After an update on the firebase side, the databaseURL doesn't  initially show up  in the firebaseConfig variable. After manually creating a Realtime Database (go to the Realtime Database tab and click on create a database) the databaseURL property showed up in my web app config in the console.

However I'm still facing a problem when filling the contact form and trying to send it (Sorry, there is an instability, try again later, or contact me via email or social media.). The web application was deployed on Firebase and the firebaseConfig variable was changed in both config and production. Thank you in advance.

**Comment by Yaccoub** [comment]
Hi 
I resolved the problem by modifying the writing rule of the firebase datastore for anyone facing the same problem :=)

**Comment by guilhermeborgesbastos** [comment]
Hello @Yaccoub, yes, the writing rule of the firebase datastore has to be adjusted. I am glad you were able to solve it. Therefore, I will close this issue.
