### ISSUE TITLE
Instructions to deploy as static site to Netlify

### ISSUE THREAD

**Issue by harshsinghal** [guilhermeborgesbastos/live-resume#39]
Love this project.

Can I deploy this project as a static site to hosts like Netlify?

**Comment by guilhermeborgesbastos** [comment]
I'm glad you've enjoyed it! For sure, go ahead! Pls, let me know if I can help you with anything.

**Comment by guilhermeborgesbastos** [comment]
Closed since there was no interaction on the ticket.
