### ISSUE TITLE
error in last setup step.

### ISSUE THREAD

**Issue by pranav1204** [guilhermeborgesbastos/live-resume#98]
ng : The term 'ng' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ng serve --host 0.0.0.0 --configuration=en
+ ~~
    + CategoryInfo          : ObjectNotFound: (ng:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by pranav1204** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/91304837/148172097-daeb3e99-fc21-41ee-bab2-2349c3ec5aa4.png">
i have run the cmd but it is not compiling anything.

**Comment by guilhermeborgesbastos** [comment]
@pranav1204, this issue is related to this other Closed issue:
https://github.com/guilhermeborgesbastos/live-resume/issues/99
