### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by pranav1204** [guilhermeborgesbastos/live-resume#99]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/91304837/148172211-a7f12668-3cda-4c7d-8303-b3f2c2fffc8a.png">
i have run the cmd but it is not compiling anything and also not returning any error.

**Comment by guilhermeborgesbastos** [comment]
@pranav1204 , I noticed an issue with some of the dependency-bot updates. I will check and fix it ASAP... Thank you for engaging... :)

**Comment by guilhermeborgesbastos** [comment]
@pranav1204, the issue has been fixed and it is already available on _master_ branch. A third person tested it, and it worked for her also.

Please, make sure to have no npm caches. 
Thank you for all.

**Comment by guilhermeborgesbastos** [comment]
@pranav1204, since there were no further issues mentioned. I will close this issue.

Please, in case of any issues, just let me know. :)

**Comment by pranav1204** [comment]
> @pranav1204, since there were no further issues mentioned. I will close this issue.
> 
> Please, in case of any issues, just let me know. :)

I have try it once again but same error occur again can you please help me with it?

**Comment by pranav1204** [comment]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/91304837/150373609-64182204-7e5e-4769-be62-23e3442f4bd2.png">
